/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_final_smart_player;

/**
 *
 * @author grija
 */
public class PANEL_BUISCAR extends javax.swing.JPanel {

    /**
     * Creates new form PANEL_BUISCAR
     */
    RESPRODUCTORMP3 principal;
    
    public PANEL_BUISCAR() {
        initComponents();
    }
    public PANEL_BUISCAR(RESPRODUCTORMP3 principal) {
    initComponents();
    this.principal = principal;
    
    COMBOX.addItem("InOrden ABB");
        COMBOX.addItem("PreOrden ABB");
        COMBOX.addItem("PostOrden ABB");
        COMBOX.addItem("InOrden AVL");
        COMBOX.addItem("PreOrden AVL");
        COMBOX.addItem("PostOrden AVL");

        TXT_RESULTADO.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT_BUSCARCAN = new javax.swing.JTextField();
        COMBOX = new javax.swing.JComboBox<>();
        BTN_ARBOLES = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXT_RESULTADO = new javax.swing.JTextArea();
        BTN_MOSTARRECORERIDOS = new javax.swing.JButton();
        BTN_ARTISTA = new javax.swing.JButton();
        BTN_GENERO = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TXT_RECORRRIDOSSS = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        TXT_BUSCARCAN.setBackground(new java.awt.Color(0, 0, 0));

        COMBOX.setBackground(new java.awt.Color(0, 0, 0));

        BTN_ARBOLES.setBackground(new java.awt.Color(0, 0, 0));
        BTN_ARBOLES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancion.png"))); // NOI18N
        BTN_ARBOLES.setBorderPainted(false);
        BTN_ARBOLES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ARBOLESActionPerformed(evt);
            }
        });

        TXT_RESULTADO.setColumns(20);
        TXT_RESULTADO.setRows(5);
        jScrollPane2.setViewportView(TXT_RESULTADO);

        BTN_MOSTARRECORERIDOS.setBackground(new java.awt.Color(0, 0, 0));
        BTN_MOSTARRECORERIDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recorridos.png"))); // NOI18N
        BTN_MOSTARRECORERIDOS.setBorderPainted(false);
        BTN_MOSTARRECORERIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MOSTARRECORERIDOSActionPerformed(evt);
            }
        });

        BTN_ARTISTA.setBackground(new java.awt.Color(0, 0, 0));
        BTN_ARTISTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/artista.png"))); // NOI18N
        BTN_ARTISTA.setBorderPainted(false);
        BTN_ARTISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ARTISTAActionPerformed(evt);
            }
        });

        BTN_GENERO.setBackground(new java.awt.Color(0, 0, 0));
        BTN_GENERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/genero.png"))); // NOI18N
        BTN_GENERO.setBorderPainted(false);
        BTN_GENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GENEROActionPerformed(evt);
            }
        });

        TXT_RECORRRIDOSSS.setColumns(20);
        TXT_RECORRRIDOSSS.setRows(5);
        jScrollPane5.setViewportView(TXT_RECORRRIDOSSS);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarpor.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_ARTISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_ARBOLES, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXT_BUSCARCAN, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_MOSTARRECORERIDOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COMBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(COMBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_MOSTARRECORERIDOS))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(BTN_ARBOLES)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_ARTISTA)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(TXT_BUSCARCAN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ARBOLESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ARBOLESActionPerformed
        // TODO add your handling code here:
       String nombre = TXT_BUSCARCAN.getText().trim();

    if (nombre.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese el nombre de una cancion");
        return;
    }

    long inicioABB = System.nanoTime();
    MUSICA resultadoABB = principal.arbolABB.buscarNodo(nombre);
    long finABB = System.nanoTime();

    long inicioAVL = System.nanoTime();
    MUSICA resultadoAVL = principal.arbolAVL.buscarNodo(nombre);
    long finAVL = System.nanoTime();

    long tiempoABB = finABB - inicioABB;
    long tiempoAVL = finAVL - inicioAVL;

    if (resultadoABB != null) {

        TXT_RESULTADO.setText(
                "CANCION ENCONTRADA EXACTA"
                + "\n\nNombre: " + resultadoABB.getNombre()
                + "\nArtista: " + resultadoABB.getArtista()
                + "\nAlbum: " + resultadoABB.getAlbum()
                + "\nGenero: " + resultadoABB.getGenero()
                + "\nAño: " + resultadoABB.getAnio()
                + "\nDuracion: " + resultadoABB.getDuracion()
                + "\nRuta: " + resultadoABB.getRuta()
                + "\n\nTiempo ABB: " + tiempoABB + " ns"
                + "\nTiempo AVL: " + tiempoAVL + " ns"
        );

    } else {

        String parecidos = principal.arbolABB.buscarParecido(nombre);

        if (parecidos.equals("")) {
            TXT_RESULTADO.setText(
                    "No se encontro la cancion"
                    + "\n\nTiempo ABB: " + tiempoABB + " ns"
                    + "\nTiempo AVL: " + tiempoAVL + " ns"
            );
        } else {
            TXT_RESULTADO.setText(
                    "No se encontro exacta, pero hay coincidencias:\n\n"
                    + parecidos
                    + "\nTiempo ABB: " + tiempoABB + " ns"
                    + "\nTiempo AVL: " + tiempoAVL + " ns"
            );
        }
    }
    }//GEN-LAST:event_BTN_ARBOLESActionPerformed

    private void BTN_MOSTARRECORERIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MOSTARRECORERIDOSActionPerformed
        // TODO add your handling code here:
          if (COMBOX.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un recorrido");
        return;
    }

    String opcion = COMBOX.getSelectedItem().toString();
    String texto = "";

    if (opcion.equals("InOrden ABB")) {
        texto = principal.arbolABB.recorridoInOrden();

    } else if (opcion.equals("PreOrden ABB")) {
        texto = principal.arbolABB.recorridoPreOrden();

    } else if (opcion.equals("PostOrden ABB")) {
        texto = principal.arbolABB.recorridoPostOrden();

    } else if (opcion.equals("InOrden AVL")) {
        texto = principal.arbolAVL.recorridoInOrden();

    } else if (opcion.equals("PreOrden AVL")) {
        texto = principal.arbolAVL.recorridoPreOrden();

    } else if (opcion.equals("PostOrden AVL")) {
        texto = principal.arbolAVL.recorridoPostOrden();
    }

    if (texto.equals("")) {
        TXT_RECORRRIDOSSS.setText("El arbol esta vacio");
    } else {
        TXT_RECORRRIDOSSS.setText("RECORRIDO: " + opcion + "\n\n" + texto);
    }
    }//GEN-LAST:event_BTN_MOSTARRECORERIDOSActionPerformed

    private void BTN_ARTISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ARTISTAActionPerformed
        // TODO add your handling code here:
            String texto = TXT_BUSCARCAN.getText();

    if (texto.trim().equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un artista para buscar");
        return;
    }

    long inicio = System.nanoTime();
    String resultado = principal.hashArtista.buscarParecido(texto);
    long fin = System.nanoTime();

    long tiempo = fin - inicio;

    TXT_RESULTADO.setText(
            "BUSQUEDA POR ARTISTA\n\n"
            + resultado
            + "\nTiempo tabla hash: " + tiempo + " ns"
    );
    }//GEN-LAST:event_BTN_ARTISTAActionPerformed

    private void BTN_GENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GENEROActionPerformed
        // TODO add your handling code here:
         String texto = TXT_BUSCARCAN.getText();

    if (texto.trim().equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un genero para buscar");
        return;
    }

    long inicio = System.nanoTime();
    String resultado = principal.hashGenero.buscarParecido(texto);
    long fin = System.nanoTime();

    long tiempo = fin - inicio;

    TXT_RESULTADO.setText(
            "BUSQUEDA POR GENERO\n\n"
            + resultado
            + "\nTiempo tabla hash: " + tiempo + " ns"
    );
    }//GEN-LAST:event_BTN_GENEROActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ARBOLES;
    private javax.swing.JButton BTN_ARTISTA;
    private javax.swing.JButton BTN_GENERO;
    private javax.swing.JButton BTN_MOSTARRECORERIDOS;
    private javax.swing.JComboBox<String> COMBOX;
    private javax.swing.JTextField TXT_BUSCARCAN;
    private javax.swing.JTextArea TXT_RECORRRIDOSSS;
    private javax.swing.JTextArea TXT_RESULTADO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
