/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_final_smart_player;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author grija
 */
public class PANEL_COLA extends javax.swing.JPanel {

    /**
     * Creates new form PANEL_COLA
     */
    RESPRODUCTORMP3 principal;
    PANEL_COLA panelCola;

        public PANEL_COLA() {
               initComponents();
               
           }

    public PANEL_COLA(RESPRODUCTORMP3 principal) {
         initComponents();
    this.principal = principal;

    String columnas[] = {"Nombre", "Artista", "Album", "Genero", "Año", "Duracion", "Tamaño", "Ruta"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);
    TABLACOLA.setModel(modelo);

    actualizarTablaCola();
             estiloTablaSpotify();
    }
    
    public void actualizarTablaCola() {

    DefaultTableModel modelo = (DefaultTableModel) TABLACOLA.getModel();
    modelo.setRowCount(0);

    nodo_coola aux = principal.cola.inicio;

    while (aux != null) {

        Object fila[] = new Object[8];

        fila[0] = aux.musica.getNombre();
        fila[1] = aux.musica.getArtista();
        fila[2] = aux.musica.getAlbum();
        fila[3] = aux.musica.getGenero();
        fila[4] = aux.musica.getAnio();
        fila[5] = aux.musica.getDuracion();
        fila[6] = aux.musica.getTamanioMB();
        fila[7] = aux.musica.getRuta();

        modelo.addRow(fila);

        aux = aux.siguiente;
    }
}
    
    private void estiloTablaSpotify() {

    TABLACOLA.setBackground(new Color(0, 0, 0));
    TABLACOLA.setForeground(Color.WHITE);
    TABLACOLA.setGridColor(new Color(35, 35, 35));

    
    TABLACOLA.setSelectionBackground(new Color(180, 0, 0)); // cuadno se oprime se pone rojo

    TABLACOLA.setRowHeight(35);
    TABLACOLA.setShowGrid(true);
    TABLACOLA.setOpaque(true);
    TABLACOLA.setFillsViewportHeight(true);

    jScrollPane1.getViewport().setBackground(new Color(0, 0, 0));
    jScrollPane1.setBackground(new Color(0, 0, 0));
    jScrollPane1.setBorder(null);

    JTableHeader header = TABLACOLA.getTableHeader();
    header.setBackground(new Color(15, 15, 15));
    header.setForeground(Color.WHITE);
    header.setOpaque(true);

    header.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            label.setBackground(new Color(15, 15, 15));
            label.setForeground(Color.RED);
            label.setHorizontalAlignment(JLabel.CENTER);
            label.setOpaque(true);

            return label;
        }
    });

    DefaultTableCellRenderer render = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            if (isSelected) {
                c.setBackground(new Color(180, 0, 0)); // Rojo 
                c.setForeground(Color.WHITE);
            } else {
                c.setBackground(new Color(0, 0, 0));   // fondo negro
                c.setForeground(Color.WHITE);
            }

            return c;
        }
    };

    for (int i = 0; i < TABLACOLA.getColumnCount(); i++) {
        TABLACOLA.getColumnModel().getColumn(i).setCellRenderer(render);
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TABLACOLA = new javax.swing.JTable();
        BTN_LIMPAIRT = new javax.swing.JButton();
        BTN_OPLAY = new javax.swing.JButton();
        BTN_LIMINAR = new javax.swing.JButton();

        TABLACOLA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TABLACOLA);

        BTN_LIMPAIRT.setText("LIMPIAR COLA");
        BTN_LIMPAIRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMPAIRTActionPerformed(evt);
            }
        });

        BTN_OPLAY.setText("PLAY");
        BTN_OPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_OPLAYActionPerformed(evt);
            }
        });

        BTN_LIMINAR.setText("ELIMINAR");
        BTN_LIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_OPLAY)
                        .addGap(37, 37, 37)
                        .addComponent(BTN_LIMINAR)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_LIMPAIRT))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_LIMPAIRT)
                    .addComponent(BTN_OPLAY)
                    .addComponent(BTN_LIMINAR))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_OPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_OPLAYActionPerformed
        // TODO add your handling code here:
        
       
       MUSICA musica = principal.cola.abajo();

    if (musica == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "La cola esta vacia");
        return;
    }

    principal.mp3.reproducir(musica.getRuta());

    principal.historial.apilar(musica);

    actualizarTablaCola();
    }//GEN-LAST:event_BTN_OPLAYActionPerformed

    private void BTN_LIMPAIRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMPAIRTActionPerformed
        // TODO add your handling code here:
        principal.cola.limpiar();
     actualizarTablaCola();

    javax.swing.JOptionPane.showMessageDialog(this, "Cola limpiada correctamente");
    }//GEN-LAST:event_BTN_LIMPAIRTActionPerformed

    private void BTN_LIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LIMINARActionPerformed
        // TODO add your handling code here:
        int fila = TABLACOLA.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cancion de la cola");
        return;
    }

    String ruta = TABLACOLA.getValueAt(fila, 7).toString();

    principal.cola.eliminarPorRuta(ruta);

    actualizarTablaCola();

    javax.swing.JOptionPane.showMessageDialog(this, "Cancion eliminada de la cola");
    }//GEN-LAST:event_BTN_LIMINARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LIMINAR;
    private javax.swing.JButton BTN_LIMPAIRT;
    private javax.swing.JButton BTN_OPLAY;
    private javax.swing.JTable TABLACOLA;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
