/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyecto_final_smart_player;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author grija
 */
public class PANEL_BUISCAR extends javax.swing.JPanel {

    /**
     * Creates new form PANEL_BUISCAR
     */
    RESPRODUCTORMP3 principal;
    
    public PANEL_BUISCAR() {
        initComponents();
    }
    public PANEL_BUISCAR(RESPRODUCTORMP3 principal) {
    initComponents();
    this.principal = principal;
    String columnas[] = {"Nombre", "Artista", "Album", "Genero", "Año", "Duracion", "Tamaño MB", "Ruta"};

    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    tablaBusqueda.setModel(modelo);
    
    COMBOX.addItem("InOrden ABB");
        COMBOX.addItem("PreOrden ABB");
        COMBOX.addItem("PostOrden ABB");
        COMBOX.addItem("InOrden AVL");
        COMBOX.addItem("PreOrden AVL");
        COMBOX.addItem("PostOrden AVL");

        TXT_RESULTADO.setEditable(false);
        estiloTablaSpotify();
   }
    
    
    
 private void estiloTablaSpotify() {

    tablaBusqueda.setBackground(new Color(0, 0, 0));
    tablaBusqueda.setForeground(Color.WHITE);
    tablaBusqueda.setGridColor(new Color(35, 35, 35));

    
    tablaBusqueda.setSelectionBackground(new Color(180, 0, 0)); // cuadno se oprime se pone rojo

    tablaBusqueda.setRowHeight(35);
    tablaBusqueda.setShowGrid(true);
    tablaBusqueda.setOpaque(true);
    tablaBusqueda.setFillsViewportHeight(true);

    jScrollPane1.getViewport().setBackground(new Color(0, 0, 0));
    jScrollPane1.setBackground(new Color(0, 0, 0));
    jScrollPane1.setBorder(null);

    JTableHeader header = tablaBusqueda.getTableHeader();
    header.setBackground(new Color(15, 15, 15));
    header.setForeground(Color.WHITE);
    header.setOpaque(true);

    header.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            label.setBackground(new Color(15, 15, 15));
            label.setForeground(Color.RED);
            label.setHorizontalAlignment(JLabel.CENTER);
            label.setOpaque(true);

            return label;
        }
    });

    DefaultTableCellRenderer render = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            if (isSelected) {
                c.setBackground(new Color(180, 0, 0)); // Rojo 
                c.setForeground(Color.WHITE);
            } else {
                c.setBackground(new Color(0, 0, 0));   // fondo negro
                c.setForeground(Color.WHITE);
            }

            return c;
        }
    };
     for (int i = 0; i < tablaBusqueda.getColumnCount(); i++) {
        tablaBusqueda.getColumnModel().getColumn(i).setCellRenderer(render);
    }
}
 
 public MUSICA obtenerMusicaDeTablaBusqueda(int fila) {
    String nombre = tablaBusqueda.getValueAt(fila, 0).toString();
    String artista = tablaBusqueda.getValueAt(fila, 1).toString();
    String album = tablaBusqueda.getValueAt(fila, 2).toString();
    String genero = tablaBusqueda.getValueAt(fila, 3).toString();
    int anio = Integer.parseInt(tablaBusqueda.getValueAt(fila, 4).toString());
    String duracion = tablaBusqueda.getValueAt(fila, 5).toString();
    double tamanio = Double.parseDouble(tablaBusqueda.getValueAt(fila, 6).toString());
    String ruta = tablaBusqueda.getValueAt(fila, 7).toString();
    MUSICA musica = new MUSICA(nombre, artista, album, genero, anio, duracion, tamanio, ruta);
    return musica;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT_BUSCARCAN = new javax.swing.JTextField();
        COMBOX = new javax.swing.JComboBox<>();
        BTN_ARBOLES = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXT_RESULTADO = new javax.swing.JTextArea();
        BTN_MOSTARRECORERIDOS = new javax.swing.JButton();
        BTN_ARTISTA = new javax.swing.JButton();
        BTN_GENERO = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TXT_RECORRRIDOSSS = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusqueda = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        TXT_BUSCARCAN.setBackground(new java.awt.Color(0, 0, 0));

        COMBOX.setBackground(new java.awt.Color(0, 0, 0));

        BTN_ARBOLES.setBackground(new java.awt.Color(0, 0, 0));
        BTN_ARBOLES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancion.png"))); // NOI18N
        BTN_ARBOLES.setBorderPainted(false);
        BTN_ARBOLES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ARBOLESActionPerformed(evt);
            }
        });

        TXT_RESULTADO.setBackground(new java.awt.Color(0, 0, 0));
        TXT_RESULTADO.setColumns(20);
        TXT_RESULTADO.setRows(5);
        jScrollPane2.setViewportView(TXT_RESULTADO);

        BTN_MOSTARRECORERIDOS.setBackground(new java.awt.Color(0, 0, 0));
        BTN_MOSTARRECORERIDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recorridos.png"))); // NOI18N
        BTN_MOSTARRECORERIDOS.setBorderPainted(false);
        BTN_MOSTARRECORERIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MOSTARRECORERIDOSActionPerformed(evt);
            }
        });

        BTN_ARTISTA.setBackground(new java.awt.Color(0, 0, 0));
        BTN_ARTISTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/artista.png"))); // NOI18N
        BTN_ARTISTA.setBorderPainted(false);
        BTN_ARTISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ARTISTAActionPerformed(evt);
            }
        });

        BTN_GENERO.setBackground(new java.awt.Color(0, 0, 0));
        BTN_GENERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/genero.png"))); // NOI18N
        BTN_GENERO.setBorderPainted(false);
        BTN_GENERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GENEROActionPerformed(evt);
            }
        });

        TXT_RECORRRIDOSSS.setBackground(new java.awt.Color(0, 0, 0));
        TXT_RECORRRIDOSSS.setColumns(20);
        TXT_RECORRRIDOSSS.setRows(5);
        jScrollPane5.setViewportView(TXT_RECORRRIDOSSS);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscarpor.png"))); // NOI18N

        tablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaBusqueda);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(TXT_BUSCARCAN, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(BTN_ARBOLES, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(BTN_ARTISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(BTN_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_MOSTARRECORERIDOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COMBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(COMBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_MOSTARRECORERIDOS))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_BUSCARCAN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN_ARBOLES)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BTN_ARTISTA)
                                    .addComponent(BTN_GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ARBOLESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ARBOLESActionPerformed
        // TODO add your handling code here:
      
    String nombre = TXT_BUSCARCAN.getText().trim();

    if (nombre.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(principal, "Ingrese el nombre de una cancion");
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tablaBusqueda.getModel();
    modelo.setRowCount(0);

    long inicioABB = System.nanoTime();
    MUSICA resultadoABB = principal.arbolABB.buscarNodo(nombre);
    long finABB = System.nanoTime();

    long inicioAVL = System.nanoTime();
    MUSICA resultadoAVL = principal.arbolAVL.buscarNodo(nombre);
    long finAVL = System.nanoTime();

    long tiempoABB = finABB - inicioABB;
    long tiempoAVL = finAVL - inicioAVL;

    if (resultadoABB != null) {

        TXT_RESULTADO.setText(
                "CANCION ENCONTRADA EXACTA"
                + "\n\nNombre: " + resultadoABB.getNombre()
                + "\nArtista: " + resultadoABB.getArtista()
                + "\nAlbum: " + resultadoABB.getAlbum()
                + "\nGenero: " + resultadoABB.getGenero()
                + "\nAño: " + resultadoABB.getAnio()
                + "\nDuracion: " + resultadoABB.getDuracion()
                + "\nRuta: " + resultadoABB.getRuta()
                + "\n\nTiempo ABB: " + tiempoABB + " ns"
                + "\nTiempo AVL: " + tiempoAVL + " ns"
        );

        Object fila[] = new Object[8];
        fila[0] = resultadoABB.getNombre();
        fila[1] = resultadoABB.getArtista();
        fila[2] = resultadoABB.getAlbum();
        fila[3] = resultadoABB.getGenero();
        fila[4] = resultadoABB.getAnio();
        fila[5] = resultadoABB.getDuracion();
        fila[6] = resultadoABB.getTamanioMB();
        fila[7] = resultadoABB.getRuta();

        modelo.addRow(fila);

    } else {

        String parecidos = principal.arbolABB.buscarParecido(nombre);

        if (parecidos.equals("")) {
            TXT_RESULTADO.setText(
                    "No se encontro la cancion"
                    + "\n\nTiempo ABB: " + tiempoABB + " ns"
                    + "\nTiempo AVL: " + tiempoAVL + " ns"
            );
        } else {
            TXT_RESULTADO.setText(
                    "No se encontro exacta, pero hay coincidencias:\n\n"
                    + parecidos
                    + "\nTiempo ABB: " + tiempoABB + " ns"
                    + "\nTiempo AVL: " + tiempoAVL + " ns"
            );

            principal.arbolABB.llenarTablaParecido(nombre, modelo);
        }
    }
    }//GEN-LAST:event_BTN_ARBOLESActionPerformed

    private void BTN_MOSTARRECORERIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MOSTARRECORERIDOSActionPerformed
        // TODO add your handling code here:
          if (COMBOX.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un recorrido");
        return;
    }

    String opcion = COMBOX.getSelectedItem().toString();
    String texto = "";

    if (opcion.equals("InOrden ABB")) {
        texto = principal.arbolABB.recorridoInOrden();

    } else if (opcion.equals("PreOrden ABB")) {
        texto = principal.arbolABB.recorridoPreOrden();

    } else if (opcion.equals("PostOrden ABB")) {
        texto = principal.arbolABB.recorridoPostOrden();

    } else if (opcion.equals("InOrden AVL")) {
        texto = principal.arbolAVL.recorridoInOrden();

    } else if (opcion.equals("PreOrden AVL")) {
        texto = principal.arbolAVL.recorridoPreOrden();

    } else if (opcion.equals("PostOrden AVL")) {
        texto = principal.arbolAVL.recorridoPostOrden();
    }

    if (texto.equals("")) {
        TXT_RECORRRIDOSSS.setText("El arbol esta vacio");
    } else {
        TXT_RECORRRIDOSSS.setText("RECORRIDO: " + opcion + "\n\n" + texto);
    }
    }//GEN-LAST:event_BTN_MOSTARRECORERIDOSActionPerformed

    private void BTN_ARTISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ARTISTAActionPerformed
        // TODO add your handling code here:
           String texto = TXT_BUSCARCAN.getText();

    if (texto.trim().equals("")) {
        javax.swing.JOptionPane.showMessageDialog(principal, "Ingrese un artista para buscar");
        return;
    }

    long inicio = System.nanoTime();
    String resultado = principal.hashArtista.buscarParecido(texto);
    long fin = System.nanoTime();

    long tiempo = fin - inicio;

    TXT_RESULTADO.setText(
            "BUSQUEDA POR ARTISTA\n\n"
            + resultado
            + "\nTiempo tabla hash: " + tiempo + " ns"
    );

    DefaultTableModel modelo = (DefaultTableModel) tablaBusqueda.getModel();
    principal.hashArtista.llenarTablaParecido(texto, modelo);
    }//GEN-LAST:event_BTN_ARTISTAActionPerformed

    private void BTN_GENEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GENEROActionPerformed
        // TODO add your handling code here:
        String texto = TXT_BUSCARCAN.getText();

    if (texto.trim().equals("")) {
        javax.swing.JOptionPane.showMessageDialog(principal, "Ingrese un genero para buscar");
        return;
    }

    long inicio = System.nanoTime();
    String resultado = principal.hashGenero.buscarParecido(texto);
    long fin = System.nanoTime();

    long tiempo = fin - inicio;

    TXT_RESULTADO.setText(
            "BUSQUEDA POR GENERO\n\n"
            + resultado
            + "\nTiempo tabla hash: " + tiempo + " ns"
    );

    DefaultTableModel modelo = (DefaultTableModel) tablaBusqueda.getModel();
    principal.hashGenero.llenarTablaParecido(texto, modelo);
    }//GEN-LAST:event_BTN_GENEROActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          int fila = tablaBusqueda.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(principal, "Seleccione una cancion de la tabla"); //resproduce la cacuioij buscada
        return;
    }
    MUSICA musica = obtenerMusicaDeTablaBusqueda(fila);
    principal.mp3.reproducir(musica.getRuta());
    principal.historial.apilar(musica);
    principal.estadisticasReproduccion.registrarReproduccion(musica);
    principal.listaDoble.ponerActualPorRuta(musica.getRuta());
    javax.swing.JOptionPane.showMessageDialog(
            principal,
            "Reproduciendo:\n" + musica.getNombre() + "\n" + musica.getArtista()
    );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        principal.mp3.detener();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ARBOLES;
    private javax.swing.JButton BTN_ARTISTA;
    private javax.swing.JButton BTN_GENERO;
    private javax.swing.JButton BTN_MOSTARRECORERIDOS;
    private javax.swing.JComboBox<String> COMBOX;
    private javax.swing.JTextField TXT_BUSCARCAN;
    private javax.swing.JTextArea TXT_RECORRRIDOSSS;
    private javax.swing.JTextArea TXT_RESULTADO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaBusqueda;
    // End of variables declaration//GEN-END:variables
}
