package com.mycompany.proyecto_final_smart_player;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author grija
 */
public class PPLAYLIST extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PPLAYLIST.class.getName());

    /**
     * Creates new form PPLAYLIST
     */
    
    MP3 mp3 = new MP3();
    PLAYLIST playlist;
    boolean circularActivo = false;


    public PPLAYLIST() {
        initComponents();
    }
    public PPLAYLIST(PLAYLIST playlist) {
        initComponents();
        
        getContentPane().setBackground(new Color(18, 18, 18));

        this.playlist = playlist;
        LABEL_NAME.setText("Playlist: " + playlist.getNombre());

        setLocationRelativeTo(null);

        String columnas[] = {"Nombre", "Artista", "Album", "Genero", "Año", "Duracion", "Tamaño MB", "Ruta"};

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        tablaPlay.setModel(modelo);

        cargarPlaylist();
        estiloTablaSpotify();
    }
    
    
   

    public void cargarPlaylist() {

    DefaultTableModel modelo = (DefaultTableModel) tablaPlay.getModel();

    modelo.setRowCount(0);

    if (playlist == null) {
        return;
    }

    NODO_PLAY aux = playlist.inicio;

    while (aux != null) {

        Object fila[] = new Object[8];

        fila[0] = aux.musica.getNombre();
        fila[1] = aux.musica.getArtista();
        fila[2] = aux.musica.getAlbum();
        fila[3] = aux.musica.getGenero();
        fila[4] = aux.musica.getAnio();
        fila[5] = aux.musica.getDuracion();
        fila[6] = aux.musica.getTamanioMB();
        fila[7] = aux.musica.getRuta();

        modelo.addRow(fila);

        aux = aux.siguiente;
    }
}
     
    private void estiloTablaSpotify() {

    tablaPlay.setBackground(new Color(0, 0, 0));
    tablaPlay.setForeground(Color.WHITE);
    tablaPlay.setGridColor(new Color(35, 35, 35));

    
    tablaPlay.setSelectionBackground(new Color(180, 0, 0)); // cuadno se oprime se pone rojo

    tablaPlay.setRowHeight(35);
    tablaPlay.setShowGrid(true);
    tablaPlay.setOpaque(true);
    tablaPlay.setFillsViewportHeight(true);

    jScrollPane1.getViewport().setBackground(new Color(0, 0, 0));
    jScrollPane1.setBackground(new Color(0, 0, 0));
    jScrollPane1.setBorder(null);

    JTableHeader header = tablaPlay.getTableHeader();
    header.setBackground(new Color(15, 15, 15));
    header.setForeground(Color.WHITE);
    header.setOpaque(true);

    header.setDefaultRenderer(new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            JLabel label = (JLabel) super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            label.setBackground(new Color(15, 15, 15));
            label.setForeground(Color.RED);
            label.setHorizontalAlignment(JLabel.CENTER);
            label.setOpaque(true);

            return label;
        }
    });

    DefaultTableCellRenderer render = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            Component c = super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);

            if (isSelected) {
                c.setBackground(new Color(180, 0, 0)); // Rojo 
                c.setForeground(Color.WHITE);
            } else {
                c.setBackground(new Color(0, 0, 0));   // fondo negro
                c.setForeground(Color.WHITE);
            }

            return c;
        }
    };
     for (int i = 0; i < tablaPlay.getColumnCount(); i++) {
        tablaPlay.getColumnModel().getColumn(i).setCellRenderer(render);
    }
}
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL_NAME = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlay = new javax.swing.JTable();
        BTN_REGRESAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BTRN_ATRAS = new javax.swing.JButton();
        BTN_PLLAY = new javax.swing.JButton();
        BTN_SIGUIENTE = new javax.swing.JButton();
        BTN_STOP = new javax.swing.JButton();
        BTN_ALEA = new javax.swing.JButton();
        BTN_ELIMINAR = new javax.swing.JButton();
        BTN_CIRULAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        LABEL_NAME.setFont(new java.awt.Font("Siemens Slab SC Black", 0, 18)); // NOI18N
        LABEL_NAME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        tablaPlay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPlay);

        BTN_REGRESAR.setText("REGRESAR");
        BTN_REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGRESARActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTRN_ATRAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ANTERIORRR.png"))); // NOI18N
        BTRN_ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTRN_ATRASActionPerformed(evt);
            }
        });

        BTN_PLLAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PLLAY.png"))); // NOI18N
        BTN_PLLAY.setBorder(null);
        BTN_PLLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PLLAYActionPerformed(evt);
            }
        });

        BTN_SIGUIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SIGUIENTEEEE.png"))); // NOI18N
        BTN_SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIGUIENTEActionPerformed(evt);
            }
        });

        BTN_STOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/STOPPP.png"))); // NOI18N
        BTN_STOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_STOPActionPerformed(evt);
            }
        });

        BTN_ALEA.setBackground(new java.awt.Color(204, 204, 204));
        BTN_ALEA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ALEARTORIA.png"))); // NOI18N
        BTN_ALEA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ALEAActionPerformed(evt);
            }
        });

        BTN_ELIMINAR.setText("ELIMINAR");
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });

        BTN_CIRULAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CIRCULARR.png"))); // NOI18N
        BTN_CIRULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CIRULARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BTRN_ATRAS, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_PLLAY, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_STOP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BTN_CIRULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BTN_ALEA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BTN_ELIMINAR)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_PLLAY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTRN_ATRAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(BTN_ELIMINAR)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BTN_STOP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_CIRULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTN_ALEA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(BTN_REGRESAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BTN_REGRESAR)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_PLLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PLLAYActionPerformed
        // TODO add your handling code here:
        
        
                int fila = tablaPlay.getSelectedRow();

          if (fila == -1) {
              javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una canción de la playlist");
          } else {
              String ruta = tablaPlay.getValueAt(fila, 7).toString();
              mp3.reproducir(ruta);
          }

        
    }//GEN-LAST:event_BTN_PLLAYActionPerformed

    private void BTN_STOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_STOPActionPerformed
        // TODO add your handling code here:
         mp3.detener();
        
    }//GEN-LAST:event_BTN_STOPActionPerformed

    private void BTN_SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIGUIENTEActionPerformed
        // TODO add your handling code here:
     
        int fila = tablaPlay.getSelectedRow();
        int totalFilas = tablaPlay.getRowCount();

        if (totalFilas == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "La playlist está vacía");
            return;
        }

        if (fila == -1) {
            fila = 0;
        } else {
            fila = fila + 1;
        }

        if (fila >= totalFilas) {

            if (circularActivo == true) {
                fila = 0;
            } else {
                mp3.detener();
                javax.swing.JOptionPane.showMessageDialog(this, "Fin de la playlist");
                return;
            }
        }

        tablaPlay.setRowSelectionInterval(fila, fila);

        String ruta = tablaPlay.getValueAt(fila, 7).toString();

        mp3.reproducir(ruta);

        
        
    }//GEN-LAST:event_BTN_SIGUIENTEActionPerformed

    private void BTRN_ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTRN_ATRASActionPerformed
        // TODO add your handling code here:
       int fila = tablaPlay.getSelectedRow();
    int totalFilas = tablaPlay.getRowCount();

    if (totalFilas == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "La playlist está vacía");
        return;
    }

    if (fila == -1) {
        fila = 0;
    } else {
        fila = fila - 1;
    }

    if (fila < 0) {

        if (circularActivo == true) {
            fila = totalFilas - 1;
        } else {
            mp3.detener();
            javax.swing.JOptionPane.showMessageDialog(this, "Inicio de la playlist");
            return;
        }
    }

    tablaPlay.setRowSelectionInterval(fila, fila);

    String ruta = tablaPlay.getValueAt(fila, 7).toString();

    mp3.reproducir(ruta);
    }//GEN-LAST:event_BTRN_ATRASActionPerformed

    private void BTN_CIRULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CIRULARActionPerformed
        // TODO add your handling code here:
        

                if (circularActivo == false) {
                    circularActivo = true;
                    BTN_CIRULAR.setText("Circular ON");
                    javax.swing.JOptionPane.showMessageDialog(this, "Modo circular activado");
                } else {
                    circularActivo = false;
                    BTN_CIRULAR.setText("Circular OFF");
                    javax.swing.JOptionPane.showMessageDialog(this, "Modo circular desactivado");
                }
    }//GEN-LAST:event_BTN_CIRULARActionPerformed

    private void BTN_REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGRESARActionPerformed
        // TODO add your handling code here:
        mp3.detener();
          this.dispose();

    }//GEN-LAST:event_BTN_REGRESARActionPerformed

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
          int fila = tablaPlay.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una canción para eliminar");
        return;
    }

    String nombreCancion = tablaPlay.getValueAt(fila, 0).toString();

    int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro que desea eliminar esta canción de la playlist?\n" + nombreCancion,
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {

        playlist.eliminar(nombreCancion);

        cargarPlaylist();

        javax.swing.JOptionPane.showMessageDialog(this, "Canción eliminada de la playlist");
    }
    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void BTN_ALEAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ALEAActionPerformed
        // TODO add your handling code here:
         int totalFilas = tablaPlay.getRowCount();

    if (totalFilas == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "La playlist está vacía");
        return;
    }

    int fila = (int) (Math.random() * totalFilas);

    tablaPlay.setRowSelectionInterval(fila, fila);

    String ruta = tablaPlay.getValueAt(fila, 7).toString();

    mp3.reproducir(ruta);
    }//GEN-LAST:event_BTN_ALEAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PPLAYLIST().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ALEA;
    private javax.swing.JButton BTN_CIRULAR;
    private javax.swing.JButton BTN_ELIMINAR;
    private javax.swing.JButton BTN_PLLAY;
    private javax.swing.JButton BTN_REGRESAR;
    private javax.swing.JButton BTN_SIGUIENTE;
    private javax.swing.JButton BTN_STOP;
    private javax.swing.JButton BTRN_ATRAS;
    private javax.swing.JLabel LABEL_NAME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPlay;
    // End of variables declaration//GEN-END:variables
}
