
package com.mycompany.proyecto_final_smart_player;
import java.awt.Color;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.CardLayout;
/**
 *
 * @author grija
 */
public class RESPRODUCTORMP3 extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RESPRODUCTORMP3.class.getName());

    /**
     * Creates new form RESPRODUCTORMP3
     */
     ARBOL_ABB arbolABB = new ARBOL_ABB();
     ARBOL_AVL arbolAVL = new ARBOL_AVL();
     MP3 mp3 = new MP3();
     String rutaCancion = "";
     LISTA_SIMPLE listaMusica = new LISTA_SIMPLE();
     LISTA_DOBLE listaDoble = new LISTA_DOBLE();
     PILA historial = new PILA();
     COLA cola = new COLA();
     LISTA_CIRCULAR listaCircular = new LISTA_CIRCULAR();
     VARIAS_PLAYS VariosPlaylist = new VARIAS_PLAYS();
     PORTADA_MP3 portadaMP3 = new PORTADA_MP3();
     
     long tiempoCargaABB = 0;
     long tiempoCargaAVL = 0;
     int totalCancionesCargadas = 0;
     
     CardLayout card;
     
     TABLA_HASH hashArtista = new TABLA_HASH(1000);
     TABLA_HASH hashGenero = new TABLA_HASH(500);
    

    PANEL_BIBLIOTECA panelBiblioteca;
    PANEL_BUISCAR panelBuscar;
    PANEL_ESTADISTICA panelEstadisticas;
    PANEL_PLAYLIST panelPlay;
    PANEL_COLA panelCola;
    
    
    public RESPRODUCTORMP3() {
        initComponents();
        
          card = new CardLayout();
        PANEL_PRINCIPAL.setLayout(card);

        panelBiblioteca = new PANEL_BIBLIOTECA(this);
        panelBuscar = new PANEL_BUISCAR(this);
        panelEstadisticas = new PANEL_ESTADISTICA(this);
        panelPlay = new PANEL_PLAYLIST(this);
        
        panelCola = new PANEL_COLA(this);
        PANEL_PRINCIPAL.add(panelCola, "cola");

        PANEL_PRINCIPAL.add(panelBiblioteca, "biblioteca");
        PANEL_PRINCIPAL.add(panelBuscar, "buscar");
        PANEL_PRINCIPAL.add(panelEstadisticas, "estadisticas");
        PANEL_PRINCIPAL.add(panelPlay, "playlist");

        card.show(PANEL_PRINCIPAL, "biblioteca");

        getContentPane().setBackground(new Color(18, 18, 18));

    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        BTN_ABRIPLAY = new javax.swing.JButton();
        BTN_BUSCAR_MUSICA = new javax.swing.JButton();
        BTN_HISTORIAL = new javax.swing.JButton();
        BTN_BIBLIOTECA = new javax.swing.JButton();
        BTN_PANELESTADIOCO = new javax.swing.JButton();
        BTN_COLA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        PANEL_PRINCIPAL = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        BTN_ABRIPLAY.setBackground(new java.awt.Color(0, 0, 0));
        BTN_ABRIPLAY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/playlist.png"))); // NOI18N
        BTN_ABRIPLAY.setBorder(null);
        BTN_ABRIPLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ABRIPLAYActionPerformed(evt);
            }
        });

        BTN_BUSCAR_MUSICA.setBackground(new java.awt.Color(0, 0, 0));
        BTN_BUSCAR_MUSICA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buiscar.png"))); // NOI18N
        BTN_BUSCAR_MUSICA.setBorder(null);
        BTN_BUSCAR_MUSICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_MUSICAActionPerformed(evt);
            }
        });

        BTN_HISTORIAL.setBackground(new java.awt.Color(0, 0, 0));
        BTN_HISTORIAL.setForeground(new java.awt.Color(255, 255, 255));
        BTN_HISTORIAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial.png"))); // NOI18N
        BTN_HISTORIAL.setBorderPainted(false);
        BTN_HISTORIAL.setContentAreaFilled(false);
        BTN_HISTORIAL.setFocusPainted(false);
        BTN_HISTORIAL.setOpaque(true);
        BTN_HISTORIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HISTORIALActionPerformed(evt);
            }
        });

        BTN_BIBLIOTECA.setBackground(new java.awt.Color(0, 0, 0));
        BTN_BIBLIOTECA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/biblioteca.png"))); // NOI18N
        BTN_BIBLIOTECA.setBorder(null);
        BTN_BIBLIOTECA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BIBLIOTECAActionPerformed(evt);
            }
        });

        BTN_PANELESTADIOCO.setBackground(new java.awt.Color(0, 0, 0));
        BTN_PANELESTADIOCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadistica.png"))); // NOI18N
        BTN_PANELESTADIOCO.setBorder(null);
        BTN_PANELESTADIOCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PANELESTADIOCOActionPerformed(evt);
            }
        });

        BTN_COLA.setBackground(new java.awt.Color(0, 0, 0));
        BTN_COLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/colas.png"))); // NOI18N
        BTN_COLA.setBorder(null);
        BTN_COLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_COLAActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bbb.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(BTN_BIBLIOTECA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_HISTORIAL))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_ABRIPLAY, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_COLA, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_PANELESTADIOCO, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_BUSCAR_MUSICA, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_BIBLIOTECA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BTN_BUSCAR_MUSICA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_HISTORIAL)
                .addGap(18, 18, 18)
                .addComponent(BTN_ABRIPLAY, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_PANELESTADIOCO)
                .addGap(18, 18, 18)
                .addComponent(BTN_COLA)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        PANEL_PRINCIPAL.setBackground(new java.awt.Color(0, 0, 0));
        PANEL_PRINCIPAL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PANEL_PRINCIPALLayout = new javax.swing.GroupLayout(PANEL_PRINCIPAL);
        PANEL_PRINCIPAL.setLayout(PANEL_PRINCIPALLayout);
        PANEL_PRINCIPALLayout.setHorizontalGroup(
            PANEL_PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1139, Short.MAX_VALUE)
        );
        PANEL_PRINCIPALLayout.setVerticalGroup(
            PANEL_PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANEL_PRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PANEL_PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_HISTORIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HISTORIALActionPerformed
        // TODO add your handling code here:

        javax.swing.JOptionPane.showMessageDialog(
            this,
            historial.obtenerHistorial(),
            "Historial de reproducción",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_BTN_HISTORIALActionPerformed

    private void BTN_BUSCAR_MUSICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_MUSICAActionPerformed
        // TODO add your handling code here:
         card.show(PANEL_PRINCIPAL, "buscar");
    }//GEN-LAST:event_BTN_BUSCAR_MUSICAActionPerformed

    private void BTN_ABRIPLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ABRIPLAYActionPerformed
        // TODO add your handling code here:
        card.show(PANEL_PRINCIPAL, "playlist");
        
        
    }//GEN-LAST:event_BTN_ABRIPLAYActionPerformed

    private void BTN_BIBLIOTECAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BIBLIOTECAActionPerformed
        // TODO add your handling code here:
        card.show(PANEL_PRINCIPAL, "biblioteca");
        
    }//GEN-LAST:event_BTN_BIBLIOTECAActionPerformed

    private void BTN_PANELESTADIOCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PANELESTADIOCOActionPerformed
        // TODO add your handling code here:
        panelEstadisticas.actualizarEstadisticas();
        card.show(PANEL_PRINCIPAL, "estadisticas");
        
    }//GEN-LAST:event_BTN_PANELESTADIOCOActionPerformed

    private void BTN_COLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_COLAActionPerformed
        // TODO add your handling code here:
        
        panelCola.actualizarTablaCola();
        card.show(PANEL_PRINCIPAL, "cola");
    }//GEN-LAST:event_BTN_COLAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       UIManager.setLookAndFeel(new FlatDarkLaf());
        java.awt.EventQueue.invokeLater(() -> new RESPRODUCTORMP3().setVisible(true));
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ABRIPLAY;
    private javax.swing.JButton BTN_BIBLIOTECA;
    private javax.swing.JButton BTN_BUSCAR_MUSICA;
    private javax.swing.JButton BTN_COLA;
    private javax.swing.JButton BTN_HISTORIAL;
    private javax.swing.JButton BTN_PANELESTADIOCO;
    private javax.swing.JPanel PANEL_PRINCIPAL;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
 


}
