
package com.mycompany.proyecto_final_smart_player;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author grija
 */
public class RESPRODUCTORMP3 extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RESPRODUCTORMP3.class.getName());

    /**
     * Creates new form RESPRODUCTORMP3
     */
    
       MP3 mp3 = new MP3();
     String rutaCancion = "";
     LISTA_SIMPLE listaMusica = new LISTA_SIMPLE();
     LISTA_DOBLE listaDoble = new LISTA_DOBLE();
     PILA historial = new PILA();
     COLA cola = new COLA();
     LISTA_CIRCULAR listaCircular = new LISTA_CIRCULAR();
    
    public RESPRODUCTORMP3() {
        initComponents();
        
    String columnas[] = {"Nombre", "Artista", "Album", "Genero", "Anio", "Duracion", "Tamano", "Ruta"};

    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    tablaMusica.setModel(modelo);
    }
    
    
    
    public void agregarMusicaATabla(MUSICA musica) {

        DefaultTableModel modelo = (DefaultTableModel) tablaMusica.getModel();

        Object fila[] = new Object[8];

        fila[0] = musica.getNombre();
        fila[1] = musica.getArtista();
        fila[2] = musica.getAlbum();
        fila[3] = musica.getGenero();
        fila[4] = musica.getAnio();
        fila[5] = musica.getDuracion();
        fila[6] = musica.getTamanioMB();
        fila[7] = musica.getRuta();

        modelo.addRow(fila);
    }
    
    
    
    
    public void cargarMusicaDeCarpeta(java.io.File carpeta) {

    java.io.File archivos[] = carpeta.listFiles();

    if (archivos != null) {

        for (int i = 0; i < archivos.length; i++) {

            if (archivos[i].isDirectory()) {

                cargarMusicaDeCarpeta(archivos[i]);

            } else {

                String nombreArchivo = archivos[i].getName().toLowerCase();

                if (nombreArchivo.endsWith(".mp3")) {

                    String ruta = archivos[i].getAbsolutePath();

                    DATOS_MP3 datos = new DATOS_MP3();
                    MUSICA musica = datos.leerDatos(ruta);

                    listaMusica.agregar(musica);
                    listaDoble.agregar(musica);
                    listaCircular.agregar(musica);

                    agregarMusicaATabla(musica);
                }
            }
        }
    }
}
    
        public MUSICA obtenerMusicaDeTabla(int fila) {

        String nombre = tablaMusica.getValueAt(fila, 0).toString();
        String artista = tablaMusica.getValueAt(fila, 1).toString();
        String album = tablaMusica.getValueAt(fila, 2).toString();
        String genero = tablaMusica.getValueAt(fila, 3).toString();
        int anio = Integer.parseInt(tablaMusica.getValueAt(fila, 4).toString());
        String duracion = tablaMusica.getValueAt(fila, 5).toString();
        double tamanio = Double.parseDouble(tablaMusica.getValueAt(fila, 6).toString());
        String ruta = tablaMusica.getValueAt(fila, 7).toString();

        MUSICA musica = new MUSICA(nombre, artista, album, genero, anio, duracion, tamanio, ruta);

        return musica;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        BTON_STOP = new javax.swing.JButton();
        BTN_SIGUIENTE = new javax.swing.JButton();
        BTN_ANTERIOR = new javax.swing.JButton();
        BTN_PLAY_MUSICA = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jToggleButton1 = new javax.swing.JToggleButton();
        BTN_CIRULAR = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        BTN_BUSCAR_MUSICA = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMusica = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTN_CARGARCAPETA = new javax.swing.JButton();
        BTN_HISTORIAL = new javax.swing.JButton();
        BTN_COLA = new javax.swing.JButton();
        btn_verCOLA = new javax.swing.JButton();
        BNT_REPROCOLA = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BTON_STOP.setText("STOP");
        BTON_STOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTON_STOPActionPerformed(evt);
            }
        });

        BTN_SIGUIENTE.setText("SIGUIENTE");
        BTN_SIGUIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIGUIENTEActionPerformed(evt);
            }
        });

        BTN_ANTERIOR.setText("ANTERIOR");
        BTN_ANTERIOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ANTERIORActionPerformed(evt);
            }
        });

        BTN_PLAY_MUSICA.setText("PLAY");
        BTN_PLAY_MUSICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PLAY_MUSICAActionPerformed(evt);
            }
        });

        jToggleButton1.setText("jToggleButton1");

        BTN_CIRULAR.setText("CIRCULAR");
        BTN_CIRULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CIRULARActionPerformed(evt);
            }
        });

        jToggleButton3.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BTN_ANTERIOR, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTON_STOP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_PLAY_MUSICA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BTN_CIRULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_ANTERIOR, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTON_STOP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SIGUIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_PLAY_MUSICA, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_CIRULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BTN_BUSCAR_MUSICA.setText("BUSCAR");
        BTN_BUSCAR_MUSICA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCAR_MUSICAActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tablaMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaMusica);

        jLabel1.setText("jLabel1");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        BTN_CARGARCAPETA.setText("CARGAR CARPETA");
        BTN_CARGARCAPETA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CARGARCAPETAActionPerformed(evt);
            }
        });

        BTN_HISTORIAL.setText("HISTORIAL");
        BTN_HISTORIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HISTORIALActionPerformed(evt);
            }
        });

        BTN_COLA.setText("AÑADIR A COLA");
        BTN_COLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_COLAActionPerformed(evt);
            }
        });

        btn_verCOLA.setText("VER COLA");
        btn_verCOLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verCOLAActionPerformed(evt);
            }
        });

        BNT_REPROCOLA.setText("REPROCOLA");
        BNT_REPROCOLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT_REPROCOLAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_CARGARCAPETA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_HISTORIAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_COLA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_verCOLA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BNT_REPROCOLA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_BUSCAR_MUSICA)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN_BUSCAR_MUSICA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(BNT_REPROCOLA))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTN_CARGARCAPETA)
                        .addComponent(BTN_HISTORIAL)
                        .addComponent(BTN_COLA)
                        .addComponent(btn_verCOLA)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BUSCAR_MUSICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCAR_MUSICAActionPerformed
        // TODO add your handling code here:
        
        
            javax.swing.JFileChooser buscar = new javax.swing.JFileChooser();
            int opcion = buscar.showOpenDialog(this);

            if (opcion == javax.swing.JFileChooser.APPROVE_OPTION) {
                java.io.File archivo = buscar.getSelectedFile();

                rutaCancion = archivo.getAbsolutePath();

                javax.swing.JOptionPane.showMessageDialog(this, "Canción seleccionada: " + archivo.getName());
            }
        

            if (opcion == javax.swing.JFileChooser.APPROVE_OPTION) {

                java.io.File archivo = buscar.getSelectedFile();

                rutaCancion = archivo.getAbsolutePath();

                DATOS_MP3 datos = new DATOS_MP3();
                MUSICA musica = datos.leerDatos(rutaCancion);

                DefaultTableModel modelo = (DefaultTableModel) tablaMusica.getModel();

                Object fila[] = new Object[8];

                fila[0] = musica.getNombre();
                fila[1] = musica.getArtista();
                fila[2] = musica.getAlbum();
                fila[3] = musica.getGenero();
                fila[4] = musica.getAnio();
                fila[5] = musica.getDuracion();
                fila[6] = musica.getTamanioMB();
                fila[7] = musica.getRuta();

                modelo.addRow(fila);

                javax.swing.JOptionPane.showMessageDialog(this, "Canción agregada a la tabla");
            }

    }//GEN-LAST:event_BTN_BUSCAR_MUSICAActionPerformed

    private void BTN_PLAY_MUSICAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PLAY_MUSICAActionPerformed
        // TODO add your handling code here:
        
        
        int fila = tablaMusica.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cancion de la tabla");
        } else {
            String ruta = tablaMusica.getValueAt(fila, 7).toString();
            listaDoble.ponerActual(ruta);
            listaCircular.ponerPorRuta(ruta);
               MUSICA musica = obtenerMusicaDeTabla(fila);
             historial.apilar(musica);
            mp3.reproducir(ruta);
        }
        
    }//GEN-LAST:event_BTN_PLAY_MUSICAActionPerformed

    private void BTON_STOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTON_STOPActionPerformed
        // TODO add your handling code here:
        
         mp3.detener();
       
        
    }//GEN-LAST:event_BTON_STOPActionPerformed

    private void BTN_CARGARCAPETAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CARGARCAPETAActionPerformed
        // TODO add your handling code here:
                                                      

    javax.swing.JFileChooser buscar = new javax.swing.JFileChooser();
    buscar.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

    int opcion = buscar.showOpenDialog(this);

    if (opcion == javax.swing.JFileChooser.APPROVE_OPTION) {

        java.io.File carpeta = buscar.getSelectedFile();

        DefaultTableModel modelo = (DefaultTableModel) tablaMusica.getModel();
        modelo.setRowCount(0);

        cargarMusicaDeCarpeta(carpeta);

        javax.swing.JOptionPane.showMessageDialog(this, "Canciones cargadas correctamente");
    }

    }//GEN-LAST:event_BTN_CARGARCAPETAActionPerformed

    private void BTN_SIGUIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIGUIENTEActionPerformed
        // TODO add your handling code here:
        
          MUSICA musica = listaDoble.siguiente();

            if (musica != null) {
                mp3.reproducir(musica.getRuta());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay canción siguiente");
            }
    }//GEN-LAST:event_BTN_SIGUIENTEActionPerformed

    private void BTN_ANTERIORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ANTERIORActionPerformed
        // TODO add your handling code here:
        MUSICA musica = listaDoble.anterior();

            if (musica != null) {
                mp3.reproducir(musica.getRuta());
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay canción anterior");
            }

        
    }//GEN-LAST:event_BTN_ANTERIORActionPerformed

    private void BTN_HISTORIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HISTORIALActionPerformed
        // TODO add your handling code here:
        
              javax.swing.JOptionPane.showMessageDialog(
            this,
            historial.obtenerHistorial(),
            "Historial de reproducción",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_BTN_HISTORIALActionPerformed

    private void BTN_COLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_COLAActionPerformed
        // TODO add your handling code here:
        
            int fila = tablaMusica.getSelectedRow();

        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una cancion de la tabla");
        } else {
            MUSICA musica = obtenerMusicaDeTabla(fila);

            cola.arriba(musica);

            javax.swing.JOptionPane.showMessageDialog(this, "Cancion agregada a la cola");
        }
    }//GEN-LAST:event_BTN_COLAActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_verCOLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verCOLAActionPerformed
        // TODO add your handling code here:
        
         javax.swing.JOptionPane.showMessageDialog(
            this,
            cola.mostrarCola(),
            "Cola de reproducción",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btn_verCOLAActionPerformed

    private void BNT_REPROCOLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT_REPROCOLAActionPerformed
        // TODO add your handling code here:
        
          MUSICA musica = cola.abajo();

    if (musica == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "La cola está vacía");
    } else {
        historial.apilar(musica);
        mp3.reproducir(musica.getRuta());

        javax.swing.JOptionPane.showMessageDialog(this,
                "Reproduciendo desde cola:\n" + musica.getNombre());
    }
    }//GEN-LAST:event_BNT_REPROCOLAActionPerformed

    private void BTN_CIRULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CIRULARActionPerformed
        // TODO add your handling code here:
        
    MUSICA musica = listaCircular.siguiente();

    if (musica == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay canciones cargadas");
    } else {
        historial.apilar(musica);
        mp3.reproducir(musica.getRuta());

        javax.swing.JOptionPane.showMessageDialog(this,
                "Reproduciendo en modo circular:\n" + musica.getNombre());
    }
    }//GEN-LAST:event_BTN_CIRULARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RESPRODUCTORMP3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT_REPROCOLA;
    private javax.swing.JButton BTN_ANTERIOR;
    private javax.swing.JButton BTN_BUSCAR_MUSICA;
    private javax.swing.JButton BTN_CARGARCAPETA;
    private javax.swing.JToggleButton BTN_CIRULAR;
    private javax.swing.JButton BTN_COLA;
    private javax.swing.JButton BTN_HISTORIAL;
    private javax.swing.JButton BTN_PLAY_MUSICA;
    private javax.swing.JButton BTN_SIGUIENTE;
    private javax.swing.JButton BTON_STOP;
    private javax.swing.JButton btn_verCOLA;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTable tablaMusica;
    // End of variables declaration//GEN-END:variables
 


}
